#!/usr/bin/env python3

"""
Initial conformer generation for HessFit.

Conformers are generated by perturbing torsional coordinates while
preserving the original atom numbering and canonical Gaussian RIC
definition.

These structures are intended as starting geometries for subsequent
QM optimization.
"""

import os
import copy
import numpy as np

from ric_geometry import evaluate_ric


def read_xyz(filename):
    """Read an XYZ file."""

    with open(filename) as f:
        lines = [x.strip() for x in f if x.strip()]

    natoms = int(lines[0])

    atoms = []
    coords = []

    for line in lines[2:2 + natoms]:
        fields = line.split()

        atoms.append(fields[0])
        coords.append([
            float(fields[1]),
            float(fields[2]),
            float(fields[3])
        ])

    return atoms, np.asarray(coords, dtype=float)


def write_xyz(filename, atoms, coords, comment="HessFit conformer"):
    """Write XYZ file."""

    with open(filename, "w") as f:

        f.write(f"{len(atoms)}\n")
        f.write(comment + "\n")

        for atom, xyz in zip(atoms, coords):

            f.write(
                f"{atom:2s} "
                f"{xyz[0]: .8f} "
                f"{xyz[1]: .8f} "
                f"{xyz[2]: .8f}\n"
            )


def rotation_matrix(axis, angle):
    """
    Rodrigues rotation matrix.

    axis must be normalized.
    angle is in radians.
    """

    axis = np.asarray(axis, dtype=float)
    axis /= np.linalg.norm(axis)

    x, y, z = axis

    c = np.cos(angle)
    s = np.sin(angle)
    C = 1.0 - c

    return np.array([
        [c + x*x*C,     x*y*C - z*s, x*z*C + y*s],
        [y*x*C + z*s,   c + y*y*C,   y*z*C - x*s],
        [z*x*C - y*s,   z*y*C + x*s, c + z*z*C]
    ])


def build_graph(ric):
    """
    Build molecular graph from canonical RIC bonds.

    Returns
    -------
    graph : dict
        graph[i] = set(neighbor atom indices)

    Atom indices are zero-based internally.
    """

    graph = {
        i: set()
        for i in range(ric.natoms)
    }

    for i, j in ric.bonds:

        i -= 1
        j -= 1

        graph[i].add(j)
        graph[j].add(i)

    return graph


def is_heavy(atom):
    return atom.upper() != "H"


def connected_component(graph, start, blocked):
    """
    Return connected component after removing one bond.

    Parameters
    ----------
    graph : dict
    start : int
    blocked : tuple(int, int)
    """

    blocked = set(blocked)

    visited = set()
    stack = [start]

    while stack:

        node = stack.pop()

        if node in visited:
            continue

        visited.add(node)

        for neighbor in graph[node]:

            if {node, neighbor} == blocked:
                continue

            if neighbor not in visited:
                stack.append(neighbor)

    return visited


def candidate_rotatable_bonds(atoms, coords, ric):
    """
    Identify candidate heavy-atom bonds that can be used for
    conformer generation.

    This is deliberately conservative.

    Excluded:
        - bonds involving H
        - terminal bonds
        - ring bonds
        - very short bonds, which are likely multiple bonds

    The final QM optimization will determine the physically
    meaningful geometry.
    """

    graph = build_graph(ric)

    candidates = []

    for i1, j1 in ric.bonds:

        i = i1 - 1
        j = j1 - 1

        if not is_heavy(atoms[i]):
            continue

        if not is_heavy(atoms[j]):
            continue

        # Exclude terminal heavy-atom bonds
        if len(graph[i]) <= 1:
            continue

        if len(graph[j]) <= 1:
            continue

        # Exclude bonds that are likely multiple bonds
        bond_length = np.linalg.norm(
            coords[i] - coords[j]
        )

        if bond_length < 1.30:
            continue

        # Determine whether bond belongs to a ring
        component = connected_component(
            graph,
            i,
            (i, j)
        )

        if j in component:
            # Removing the bond did not disconnect it -> ring bond
            continue

        candidates.append((i + 1, j + 1))

    return candidates


def rotate_fragment(coords, atoms_to_rotate, atom_i, atom_j, angle_deg):
    """
    Rotate one fragment around atom_i-atom_j.

    atom_i and atom_j use 1-based numbering.
    """

    coords_new = coords.copy()

    i = atom_i - 1
    j = atom_j - 1

    origin = coords[i]
    axis = coords[j] - coords[i]

    R = rotation_matrix(
        axis,
        np.radians(angle_deg)
    )

    for atom in atoms_to_rotate:

        r = coords[atom] - origin

        coords_new[atom] = origin + np.dot(R, r)

    return coords_new


def rotate_about_bond(
    coords,
    graph,
    atom_i,
    atom_j,
    angle_deg
):
    """
    Rotate the smaller molecular fragment around i-j.
    """

    i = atom_i - 1
    j = atom_j - 1

    frag_i = connected_component(
        graph,
        i,
        (i, j)
    )

    frag_j = connected_component(
        graph,
        j,
        (i, j)
    )

    # Pick the smaller side for rotation.
    if len(frag_i) <= len(frag_j):

        rotate_atoms = frag_i
        fixed_atom = j
        moving_atom = i

    else:

        rotate_atoms = frag_j
        fixed_atom = i
        moving_atom = j

    # The rotation axis must start at the fixed atom.
    coords_new = rotate_fragment(
        coords,
        rotate_atoms,
        fixed_atom + 1,
        moving_atom + 1,
        angle_deg
    )

    return coords_new


def rmsd(coords1, coords2):
    """
    Simple coordinate RMSD.

    The geometries already have the same orientation and atom order,
    so no atom mapping is performed here.
    """

    diff = coords1 - coords2

    return np.sqrt(
        np.mean(np.sum(diff * diff, axis=1))
    )


def generate_conformers(
    atoms,
    coords,
    ric,
    n_conformers=20,
    max_rotation=180.0,
    min_rmsd=0.20,
    seed=12345
):
    """
    Generate a diverse initial conformer ensemble.

    Parameters
    ----------
    atoms
        Atom symbols.

    coords
        Reference optimized geometry.

    ric
        CanonicalRIC object.

    n_conformers
        Number of structures requested.

    max_rotation
        Maximum random torsional perturbation.

    min_rmsd
        Minimum coordinate RMSD required to retain a new conformer.

    seed
        Random seed for reproducibility.
    """

    rng = np.random.default_rng(seed)

    graph = build_graph(ric)

    rotatable = candidate_rotatable_bonds(
        atoms,
        coords,
        ric
    )

    print("\nCandidate rotatable bonds:")
    for bond in rotatable:
        print(f"  {bond[0]} - {bond[1]}")

    if not rotatable:

        print(
            "\nNo candidate rotatable bonds found. "
            "Only the reference geometry will be returned."
        )

        return [coords.copy()]

    conformers = [coords.copy()]

    attempts = 0
    max_attempts = max(1000, n_conformers * 100)

    while (
        len(conformers) < n_conformers
        and attempts < max_attempts
    ):

        attempts += 1

        candidate = coords.copy()

        # Random number of torsions to perturb.
        n_rotate = rng.integers(
            1,
            min(len(rotatable), 4) + 1
        )

        selected = rng.choice(
            len(rotatable),
            size=n_rotate,
            replace=False
        )

        for idx in selected:

            atom_i, atom_j = rotatable[idx]

            angle = rng.uniform(
                -max_rotation,
                max_rotation
            )

            candidate = rotate_about_bond(
                candidate,
                graph,
                atom_i,
                atom_j,
                angle
            )

        # Reject if too close to an existing conformer
        duplicate = False

        for existing in conformers:

            if rmsd(candidate, existing) < min_rmsd:

                duplicate = True
                break

        if duplicate:
            continue

        conformers.append(candidate)

    print(
        f"\nGenerated {len(conformers)} unique "
        f"initial conformers after {attempts} attempts."
    )

    return conformers